services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        App\Application\Service\OpenCloseServiceInterface:
            tags: [ 'app.service.test' ]

    App\:
        resource: '../src/'
        exclude:
            - '../src/Adapter/Secondary/Entity/'
            - '../src/Kernel.php'

    App\Adapter\Secondary\Purger\TestPurgerFactory:
        tags:
            - { name: 'doctrine.fixtures.purger_factory', alias: 'test_purger' }

    App\Application\Service\OpenCloseTestPolicy:
        public: true
        arguments:
            $services: !tagged app.service.test

    App\Application\Service\Test1Service:
        public: true

    App\Application\Service\DefaultTestService:
        public: true

    app.service.default:
        alias: App\Application\Service\DefaultTestService
        public: true

    app.service.test1:
        alias: App\Application\Service\Test1Service
        public: true

when@test:
    services:
        App\Tests\Support\Override\DatabaseManager:
            decorates: App\Adapter\Secondary\DatabaseManager
            arguments: ['@.inner']

        App\Tests\Support\Override\MessageBus:
            decorates: App\Adapter\Secondary\MessageQueue\MessageBus
            arguments: ['@.inner']
